try:
    if(3<4):
        raise Exception
except:
    print("异常已抛出")
